name: Check PR
on: [push]

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-cache-${{ hashFiles('project/**') }}-${{ hashFiles('**/**.sbt') }}
      - name: Cache SBT (Ivy)
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: sbt-cache-ivy-${{ hashFiles('project/**') }}-${{ hashFiles('**/**.sbt') }}
      - name: Cache SBT (Coursier)
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: sbt-cache-coursier-${{ hashFiles('project/**') }}-${{ hashFiles('**/**.sbt') }}
      - name: Check PR
        run: sbt --mem 6144 --batch checkPR
